apiVersion: v1
kind: Pod
metadata:
  name: envtest
spec:
  containers:
  - name: envtest-container
    image: busybox:1.34
    command: ["env"]
    env:
    - name: STUDENT_FIRST_NAME
      value: "Tushar"
    - name: STUDENT_LAST_NAME
      value: "Srivastava"