apiVersion: v1
kind: Pod
metadata:
  namespace: exam-check-02
  name: database-app
spec:
  initContainers:
  - name: bootstrap
    image: busybox:1.34
    command:
    - "sleep"
    - "15"
  containers:
  - name: main
    image: redis:5-alpine