apiVersion: v1
kind: Service
metadata:
  name: book-shelf-service
  namespace: prod
spec:
  selector:
    app: book-shelf
  ports:
    - protocol: TCP
      port: 80
      targetPort: 8080
  # clusterIP: 10.0.171.239 # not needed, created automatically
  type: LoadBalancer
# status:
#   loadBalancer:
#     ingress:
#     - ip: 192.0.2.127 # not needed, created automatically