apiVersion: v1
kind: Service
metadata:
  name: pod-info-svc
spec:
  type: ClusterIP
  selector:
    # key: value
    app: pod-info-app
  ports:
  - port: 80
    targetPort: 80
    # nodePort: <node_port> when spec.type is NodePort